language: python            # this works for Linux but is an error on macOS or Windows

services:
  - docker
  
before_install:
  - docker build -t 380app ./app/  
  - docker run 380app -p 80:80

install:
  - pip3 install -r requirements.txt

script:
  - pytest ./testing
