language: python            # this works for Linux but is an error on macOS or Windows

services:
  - docker
  
before_install:
  - docker-compose up -d
  
install:
  - pip install -r requirements.txt

script:
  - pytest ./testing
