language: python            # this works for Linux but is an error on macOS or Windows

services:
  - docker
  
before_install:
  - docker build -t 380app ./app/  
  - docker run -d -p 80:80 380app
  
install:
  - pip install -r requirements.txt

script:
  - pytest ./testing
